import assert from "node:assert/strict";
import playwright from "playwright";
const browser = await playwright[process.env.PYSX_BROWSER_ENGINE].launch();
try {
  const page = await browser.newPage();
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${process.argv[2]}`);
  await page.waitForSelector("#draft-alpha");
  await page.locator("#draft-alpha").fill("private draft");
  await page.locator('[data-count="alpha"]').click();
  await page.waitForFunction(() => document.querySelector('[data-count="alpha"]')?.textContent === "Count: 1");
  await page.evaluate(() => {
    const field = document.querySelector("#draft-alpha");
    field.focus(); field.setSelectionRange(2, 5, "backward");
    window.demoSaved = {field, row: document.querySelector('[data-row="alpha"]'), child: document.querySelector('[data-child="alpha:one"]'), token: field.dataset.pysxRef};
    document.querySelector("#keyed-reverse").click();
  });
  await page.waitForFunction(() => document.querySelector('[data-row]')?.dataset.row === "beta");
  assert.equal(await page.evaluate(() => window.demoSaved.field === document.querySelector("#draft-alpha") && document.activeElement === window.demoSaved.field && window.demoSaved.field.dataset.pysxRef === window.demoSaved.token), true);
  assert.deepEqual(await page.locator("#draft-alpha").evaluate(node => [node.value, node.selectionStart, node.selectionEnd, node.selectionDirection]), ["private draft", 2, 5, "backward"]);
  await page.locator('[data-focus-reverse="alpha"]').click();
  await page.waitForFunction(() => document.querySelector('[data-row]')?.dataset.row === "alpha" && document.activeElement?.id === "draft-alpha");
  console.log("  ok  public example retains refs, drafts, counts and caret through both reverse actions");
  await page.locator("#keyed-rename").click();
  await page.waitForFunction(() => document.querySelector('[data-row="alpha"]')?.title === "Alpha renamed");
  assert.equal(await page.evaluate(() => window.demoSaved.row === document.querySelector('[data-row="alpha"]') && window.demoSaved.field === document.querySelector("#draft-alpha")), true);
  assert.equal(await page.locator("#draft-alpha").inputValue(), "private draft");
  assert.equal(await page.locator('[data-count="alpha"]').textContent(), "Count: 1");
  await page.locator('[data-add="alpha"]').click();
  await page.waitForFunction(() => document.querySelectorAll('[data-row="alpha"] [data-child]').length === 3);
  assert.equal(await page.evaluate(() => window.demoSaved.child === document.querySelector('[data-child="alpha:one"]')), true);
  await page.locator('[data-child="alpha:one"]').click();
  await page.waitForFunction(() => document.querySelector("#keyed-chosen")?.textContent === "Alpha renamed / one");
  console.log("  ok  same-key labels and nested choices preserve nodes and use current callbacks");
  const other = await browser.newPage();
  await other.goto(`http://127.0.0.1:${process.argv[2]}`);
  await other.waitForSelector("#draft-alpha");
  assert.equal(await other.locator("#draft-alpha").inputValue(), "Alpha");
  assert.equal(await other.locator('[data-count="alpha"]').textContent(), "Count: 0");
  await other.close();
  await page.locator("#keyed-remove").click();
  await page.waitForFunction(() => !document.querySelector("#draft-alpha"));
  assert.equal(await page.locator('[data-draft="alpha"]').count(), 0);
  await page.locator("#keyed-restore").click();
  await page.waitForSelector("#draft-alpha");
  assert.equal(await page.locator("#draft-alpha").inputValue(), "Alpha restored");
  assert.equal(await page.locator('[data-count="alpha"]').textContent(), "Count: 0");
  assert.equal(await page.evaluate(() => !window.demoSaved.field.isConnected && window.demoSaved.field !== document.querySelector("#draft-alpha") && window.demoSaved.token !== document.querySelector("#draft-alpha").dataset.pysxRef), true);
  assert.deepEqual(errors, []);
  console.log("  ok  sessions are isolated and removed rows restart with fresh state and refs");
  console.log("KEYED ROWS EXAMPLE BROWSER PASSED");
} finally { await browser.close(); }
