"""Frozen native element markers. Typed constructors live in pysx.native."""

from dataclasses import dataclass

from .schema import VOID as VOID
from .schema import tag_info


@dataclass(frozen=True)
class ElementTag:
    name: str

    def __str__(self) -> str:
        return self.name

    @property
    def void(self) -> bool:
        info = tag_info(self.name)

        return info is not None and info.void


a = ElementTag("a")
abbr = ElementTag("abbr")
address = ElementTag("address")
area = ElementTag("area")
article = ElementTag("article")
aside = ElementTag("aside")
audio = ElementTag("audio")
b = ElementTag("b")
base = ElementTag("base")
bdi = ElementTag("bdi")
bdo = ElementTag("bdo")
blockquote = ElementTag("blockquote")
body = ElementTag("body")
br = ElementTag("br")
button = ElementTag("button")
canvas = ElementTag("canvas")
caption = ElementTag("caption")
cite = ElementTag("cite")
code = ElementTag("code")
col = ElementTag("col")
colgroup = ElementTag("colgroup")
data = ElementTag("data")
datalist = ElementTag("datalist")
dd = ElementTag("dd")
del_ = ElementTag("del")
details = ElementTag("details")
dfn = ElementTag("dfn")
dialog = ElementTag("dialog")
div = ElementTag("div")
dl = ElementTag("dl")
dt = ElementTag("dt")
em = ElementTag("em")
embed = ElementTag("embed")
fieldset = ElementTag("fieldset")
figcaption = ElementTag("figcaption")
figure = ElementTag("figure")
footer = ElementTag("footer")
form = ElementTag("form")
fragment = ElementTag("fragment")
h1 = ElementTag("h1")
h2 = ElementTag("h2")
h3 = ElementTag("h3")
h4 = ElementTag("h4")
h5 = ElementTag("h5")
h6 = ElementTag("h6")
head = ElementTag("head")
header = ElementTag("header")
hr = ElementTag("hr")
html = ElementTag("html")
i = ElementTag("i")
iframe = ElementTag("iframe")
img = ElementTag("img")
input = ElementTag("input")
ins = ElementTag("ins")
kbd = ElementTag("kbd")
label = ElementTag("label")
legend = ElementTag("legend")
li = ElementTag("li")
link = ElementTag("link")
main = ElementTag("main")
map = ElementTag("map")
mark = ElementTag("mark")
math = ElementTag("math")
menu = ElementTag("menu")
meta = ElementTag("meta")
meter = ElementTag("meter")
nav = ElementTag("nav")
noscript = ElementTag("noscript")
object = ElementTag("object")
ol = ElementTag("ol")
optgroup = ElementTag("optgroup")
option = ElementTag("option")
output = ElementTag("output")
p = ElementTag("p")
param = ElementTag("param")
picture = ElementTag("picture")
pre = ElementTag("pre")
progress = ElementTag("progress")
q = ElementTag("q")
rp = ElementTag("rp")
rt = ElementTag("rt")
ruby = ElementTag("ruby")
s = ElementTag("s")
samp = ElementTag("samp")
script = ElementTag("script")
section = ElementTag("section")
select = ElementTag("select")
slot = ElementTag("slot")
small = ElementTag("small")
source = ElementTag("source")
span = ElementTag("span")
strong = ElementTag("strong")
style = ElementTag("style")
sub = ElementTag("sub")
summary = ElementTag("summary")
sup = ElementTag("sup")
svg = ElementTag("svg")
table = ElementTag("table")
tbody = ElementTag("tbody")
td = ElementTag("td")
template = ElementTag("template")
textarea = ElementTag("textarea")
tfoot = ElementTag("tfoot")
th = ElementTag("th")
thead = ElementTag("thead")
time = ElementTag("time")
title = ElementTag("title")
tr = ElementTag("tr")
track = ElementTag("track")
u = ElementTag("u")
ul = ElementTag("ul")
var = ElementTag("var")
video = ElementTag("video")
wbr = ElementTag("wbr")
