"""Typed native constructors. Generated by scripts/generate_native.py."""
# ruff: noqa: N802, E743, TC001, TC003

from collections.abc import Callable, Mapping
from typing import TypedDict, Unpack

from .native_support import custom_element as custom_element
from .native_support import element
from .reactive import Signal
from .render import Fragment as RenderFragment


class GlobalAttrs(TypedDict, total=False):
    accesskey: str | Signal[str] | None
    autocapitalize: str | Signal[str] | None
    autofocus: bool | Signal[bool] | None
    class_name: str | Signal[str] | None
    contenteditable: str | Signal[str] | None
    dir: str | Signal[str] | None
    draggable: str | Signal[str] | None
    enterkeyhint: str | Signal[str] | None
    hidden: bool | Signal[bool] | None
    id: str | Signal[str] | None
    inert: bool | Signal[bool] | None
    inputmode: str | Signal[str] | None
    is_: str | Signal[str] | None
    itemid: str | Signal[str] | None
    itemprop: str | Signal[str] | None
    itemref: str | Signal[str] | None
    itemscope: bool | Signal[bool] | None
    itemtype: str | Signal[str] | None
    lang: str | Signal[str] | None
    nonce: str | Signal[str] | None
    part: str | Signal[str] | None
    popover: str | Signal[str] | None
    role: str | Signal[str] | None
    slot: str | Signal[str] | None
    spellcheck: str | Signal[str] | None
    style: str | Signal[str] | None
    tabindex: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    title: str | Signal[str] | None
    translate: str | Signal[str] | None
    on_abort: Callable[[object], object]
    on_animationend: Callable[[object], object]
    on_animationiteration: Callable[[object], object]
    on_animationstart: Callable[[object], object]
    on_auxclick: Callable[[object], object]
    on_beforeinput: Callable[[object], object]
    on_blur: Callable[[object], object]
    on_cancel: Callable[[object], object]
    on_canplay: Callable[[object], object]
    on_canplaythrough: Callable[[object], object]
    on_change: Callable[[object], object]
    on_click: Callable[[object], object]
    on_close: Callable[[object], object]
    on_compositionend: Callable[[object], object]
    on_compositionstart: Callable[[object], object]
    on_compositionupdate: Callable[[object], object]
    on_contextmenu: Callable[[object], object]
    on_copy: Callable[[object], object]
    on_cuechange: Callable[[object], object]
    on_cut: Callable[[object], object]
    on_dblclick: Callable[[object], object]
    on_drag: Callable[[object], object]
    on_dragend: Callable[[object], object]
    on_dragenter: Callable[[object], object]
    on_dragleave: Callable[[object], object]
    on_dragover: Callable[[object], object]
    on_dragstart: Callable[[object], object]
    on_drop: Callable[[object], object]
    on_durationchange: Callable[[object], object]
    on_emptied: Callable[[object], object]
    on_ended: Callable[[object], object]
    on_error: Callable[[object], object]
    on_focus: Callable[[object], object]
    on_focusin: Callable[[object], object]
    on_focusout: Callable[[object], object]
    on_formdata: Callable[[object], object]
    on_fullscreenchange: Callable[[object], object]
    on_gotpointercapture: Callable[[object], object]
    on_input: Callable[[object], object]
    on_invalid: Callable[[object], object]
    on_keydown: Callable[[object], object]
    on_keypress: Callable[[object], object]
    on_keyup: Callable[[object], object]
    on_load: Callable[[object], object]
    on_loadeddata: Callable[[object], object]
    on_loadedmetadata: Callable[[object], object]
    on_loadstart: Callable[[object], object]
    on_lostpointercapture: Callable[[object], object]
    on_mousedown: Callable[[object], object]
    on_mouseenter: Callable[[object], object]
    on_mouseleave: Callable[[object], object]
    on_mousemove: Callable[[object], object]
    on_mouseout: Callable[[object], object]
    on_mouseover: Callable[[object], object]
    on_mouseup: Callable[[object], object]
    on_mousewheel: Callable[[object], object]
    on_paste: Callable[[object], object]
    on_pause: Callable[[object], object]
    on_play: Callable[[object], object]
    on_playing: Callable[[object], object]
    on_pointercancel: Callable[[object], object]
    on_pointerdown: Callable[[object], object]
    on_pointerenter: Callable[[object], object]
    on_pointerleave: Callable[[object], object]
    on_pointermove: Callable[[object], object]
    on_pointerout: Callable[[object], object]
    on_pointerover: Callable[[object], object]
    on_pointerup: Callable[[object], object]
    on_progress: Callable[[object], object]
    on_ratechange: Callable[[object], object]
    on_reset: Callable[[object], object]
    on_resize: Callable[[object], object]
    on_scroll: Callable[[object], object]
    on_scrollend: Callable[[object], object]
    on_securitypolicyviolation: Callable[[object], object]
    on_seeked: Callable[[object], object]
    on_seeking: Callable[[object], object]
    on_select: Callable[[object], object]
    on_selectionchange: Callable[[object], object]
    on_selectstart: Callable[[object], object]
    on_show: Callable[[object], object]
    on_slotchange: Callable[[object], object]
    on_stalled: Callable[[object], object]
    on_submit: Callable[[object], object]
    on_suspend: Callable[[object], object]
    on_timeupdate: Callable[[object], object]
    on_toggle: Callable[[object], object]
    on_touchcancel: Callable[[object], object]
    on_touchend: Callable[[object], object]
    on_touchmove: Callable[[object], object]
    on_touchstart: Callable[[object], object]
    on_transitionend: Callable[[object], object]
    on_volumechange: Callable[[object], object]
    on_waiting: Callable[[object], object]
    on_wheel: Callable[[object], object]
    custom_attrs: Mapping[str, object]


class AAttrs(GlobalAttrs, total=False):
    download: str | Signal[str] | None
    href: str | Signal[str] | None
    hreflang: str | Signal[str] | None
    ping: str | Signal[str] | None
    referrerpolicy: str | Signal[str] | None
    rel: str | Signal[str] | None
    target: str | Signal[str] | None
    type: str | Signal[str] | None


def A(*children: object, **attrs: Unpack[AAttrs]) -> RenderFragment:
    return element("a", children, attrs)


class AbbrAttrs(GlobalAttrs, total=False):
    pass


def Abbr(*children: object, **attrs: Unpack[AbbrAttrs]) -> RenderFragment:
    return element("abbr", children, attrs)


class AddressAttrs(GlobalAttrs, total=False):
    pass


def Address(*children: object, **attrs: Unpack[AddressAttrs]) -> RenderFragment:
    return element("address", children, attrs)


class AreaAttrs(GlobalAttrs, total=False):
    alt: str | Signal[str] | None
    coords: str | Signal[str] | None
    download: str | Signal[str] | None
    href: str | Signal[str] | None
    hreflang: str | Signal[str] | None
    ping: str | Signal[str] | None
    referrerpolicy: str | Signal[str] | None
    rel: str | Signal[str] | None
    shape: str | Signal[str] | None
    target: str | Signal[str] | None


def Area(*children: object, **attrs: Unpack[AreaAttrs]) -> RenderFragment:
    return element("area", children, attrs)


class ArticleAttrs(GlobalAttrs, total=False):
    pass


def Article(*children: object, **attrs: Unpack[ArticleAttrs]) -> RenderFragment:
    return element("article", children, attrs)


class AsideAttrs(GlobalAttrs, total=False):
    pass


def Aside(*children: object, **attrs: Unpack[AsideAttrs]) -> RenderFragment:
    return element("aside", children, attrs)


class AudioAttrs(GlobalAttrs, total=False):
    autoplay: bool | Signal[bool] | None
    controls: bool | Signal[bool] | None
    crossorigin: str | Signal[str] | None
    loop: bool | Signal[bool] | None
    muted: bool | Signal[bool] | None
    preload: str | Signal[str] | None
    src: str | Signal[str] | None


def Audio(*children: object, **attrs: Unpack[AudioAttrs]) -> RenderFragment:
    return element("audio", children, attrs)


class BAttrs(GlobalAttrs, total=False):
    pass


def B(*children: object, **attrs: Unpack[BAttrs]) -> RenderFragment:
    return element("b", children, attrs)


class BaseAttrs(GlobalAttrs, total=False):
    href: str | Signal[str] | None
    target: str | Signal[str] | None


def Base(*children: object, **attrs: Unpack[BaseAttrs]) -> RenderFragment:
    return element("base", children, attrs)


class BdiAttrs(GlobalAttrs, total=False):
    pass


def Bdi(*children: object, **attrs: Unpack[BdiAttrs]) -> RenderFragment:
    return element("bdi", children, attrs)


class BdoAttrs(GlobalAttrs, total=False):
    pass


def Bdo(*children: object, **attrs: Unpack[BdoAttrs]) -> RenderFragment:
    return element("bdo", children, attrs)


class BlockquoteAttrs(GlobalAttrs, total=False):
    cite: str | Signal[str] | None


def Blockquote(*children: object, **attrs: Unpack[BlockquoteAttrs]) -> RenderFragment:
    return element("blockquote", children, attrs)


class BodyAttrs(GlobalAttrs, total=False):
    onafterprint: Callable[[object], object]
    onbeforeprint: Callable[[object], object]
    onbeforeunload: Callable[[object], object]
    onhashchange: Callable[[object], object]
    onload: Callable[[object], object]
    onpopstate: Callable[[object], object]
    onunload: Callable[[object], object]


def Body(*children: object, **attrs: Unpack[BodyAttrs]) -> RenderFragment:
    return element("body", children, attrs)


class BrAttrs(GlobalAttrs, total=False):
    pass


def Br(*children: object, **attrs: Unpack[BrAttrs]) -> RenderFragment:
    return element("br", children, attrs)


class ButtonAttrs(GlobalAttrs, total=False):
    disabled: bool | Signal[bool] | None
    form: str | Signal[str] | None
    formaction: str | Signal[str] | None
    formenctype: str | Signal[str] | None
    formmethod: str | Signal[str] | None
    formnovalidate: bool | Signal[bool] | None
    formtarget: str | Signal[str] | None
    name: str | Signal[str] | None
    popovertarget: str | Signal[str] | None
    popovertargetaction: str | Signal[str] | None
    type: str | Signal[str] | None
    value: str | Signal[str] | None


def Button(*children: object, **attrs: Unpack[ButtonAttrs]) -> RenderFragment:
    return element("button", children, attrs)


class CanvasAttrs(GlobalAttrs, total=False):
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Canvas(*children: object, **attrs: Unpack[CanvasAttrs]) -> RenderFragment:
    return element("canvas", children, attrs)


class CaptionAttrs(GlobalAttrs, total=False):
    pass


def Caption(*children: object, **attrs: Unpack[CaptionAttrs]) -> RenderFragment:
    return element("caption", children, attrs)


class CiteAttrs(GlobalAttrs, total=False):
    pass


def Cite(*children: object, **attrs: Unpack[CiteAttrs]) -> RenderFragment:
    return element("cite", children, attrs)


class CodeAttrs(GlobalAttrs, total=False):
    pass


def Code(*children: object, **attrs: Unpack[CodeAttrs]) -> RenderFragment:
    return element("code", children, attrs)


class ColAttrs(GlobalAttrs, total=False):
    span: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Col(*children: object, **attrs: Unpack[ColAttrs]) -> RenderFragment:
    return element("col", children, attrs)


class ColgroupAttrs(GlobalAttrs, total=False):
    span: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Colgroup(*children: object, **attrs: Unpack[ColgroupAttrs]) -> RenderFragment:
    return element("colgroup", children, attrs)


class DataAttrs(GlobalAttrs, total=False):
    value: str | Signal[str] | None


def Data(*children: object, **attrs: Unpack[DataAttrs]) -> RenderFragment:
    return element("data", children, attrs)


class DatalistAttrs(GlobalAttrs, total=False):
    pass


def Datalist(*children: object, **attrs: Unpack[DatalistAttrs]) -> RenderFragment:
    return element("datalist", children, attrs)


class DdAttrs(GlobalAttrs, total=False):
    pass


def Dd(*children: object, **attrs: Unpack[DdAttrs]) -> RenderFragment:
    return element("dd", children, attrs)


class DelAttrs(GlobalAttrs, total=False):
    cite: str | Signal[str] | None
    datetime: str | Signal[str] | None


def Del(*children: object, **attrs: Unpack[DelAttrs]) -> RenderFragment:
    return element("del", children, attrs)


class DetailsAttrs(GlobalAttrs, total=False):
    name: str | Signal[str] | None
    open: bool | Signal[bool] | None


def Details(*children: object, **attrs: Unpack[DetailsAttrs]) -> RenderFragment:
    return element("details", children, attrs)


class DfnAttrs(GlobalAttrs, total=False):
    pass


def Dfn(*children: object, **attrs: Unpack[DfnAttrs]) -> RenderFragment:
    return element("dfn", children, attrs)


class DialogAttrs(GlobalAttrs, total=False):
    open: bool | Signal[bool] | None


def Dialog(*children: object, **attrs: Unpack[DialogAttrs]) -> RenderFragment:
    return element("dialog", children, attrs)


class DivAttrs(GlobalAttrs, total=False):
    pass


def Div(*children: object, **attrs: Unpack[DivAttrs]) -> RenderFragment:
    return element("div", children, attrs)


class DlAttrs(GlobalAttrs, total=False):
    pass


def Dl(*children: object, **attrs: Unpack[DlAttrs]) -> RenderFragment:
    return element("dl", children, attrs)


class DtAttrs(GlobalAttrs, total=False):
    pass


def Dt(*children: object, **attrs: Unpack[DtAttrs]) -> RenderFragment:
    return element("dt", children, attrs)


class EmAttrs(GlobalAttrs, total=False):
    pass


def Em(*children: object, **attrs: Unpack[EmAttrs]) -> RenderFragment:
    return element("em", children, attrs)


class EmbedAttrs(GlobalAttrs, total=False):
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    src: str | Signal[str] | None
    type: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Embed(*children: object, **attrs: Unpack[EmbedAttrs]) -> RenderFragment:
    return element("embed", children, attrs)


class FieldsetAttrs(GlobalAttrs, total=False):
    disabled: bool | Signal[bool] | None
    form: str | Signal[str] | None
    name: str | Signal[str] | None


def Fieldset(*children: object, **attrs: Unpack[FieldsetAttrs]) -> RenderFragment:
    return element("fieldset", children, attrs)


class FigcaptionAttrs(GlobalAttrs, total=False):
    pass


def Figcaption(*children: object, **attrs: Unpack[FigcaptionAttrs]) -> RenderFragment:
    return element("figcaption", children, attrs)


class FigureAttrs(GlobalAttrs, total=False):
    pass


def Figure(*children: object, **attrs: Unpack[FigureAttrs]) -> RenderFragment:
    return element("figure", children, attrs)


class FooterAttrs(GlobalAttrs, total=False):
    pass


def Footer(*children: object, **attrs: Unpack[FooterAttrs]) -> RenderFragment:
    return element("footer", children, attrs)


class FormAttrs(GlobalAttrs, total=False):
    accept_charset: str | Signal[str] | None
    action: str | Signal[str] | None
    autocomplete: str | Signal[str] | None
    enctype: str | Signal[str] | None
    method: str | Signal[str] | None
    name: str | Signal[str] | None
    novalidate: bool | Signal[bool] | None
    rel: str | Signal[str] | None
    target: str | Signal[str] | None


def Form(*children: object, **attrs: Unpack[FormAttrs]) -> RenderFragment:
    return element("form", children, attrs)


class FragmentAttrs(TypedDict, total=False):
    pass


def Fragment(*children: object, **attrs: Unpack[FragmentAttrs]) -> RenderFragment:
    return element("fragment", children, attrs)


class H1Attrs(GlobalAttrs, total=False):
    pass


def H1(*children: object, **attrs: Unpack[H1Attrs]) -> RenderFragment:
    return element("h1", children, attrs)


class H2Attrs(GlobalAttrs, total=False):
    pass


def H2(*children: object, **attrs: Unpack[H2Attrs]) -> RenderFragment:
    return element("h2", children, attrs)


class H3Attrs(GlobalAttrs, total=False):
    pass


def H3(*children: object, **attrs: Unpack[H3Attrs]) -> RenderFragment:
    return element("h3", children, attrs)


class H4Attrs(GlobalAttrs, total=False):
    pass


def H4(*children: object, **attrs: Unpack[H4Attrs]) -> RenderFragment:
    return element("h4", children, attrs)


class H5Attrs(GlobalAttrs, total=False):
    pass


def H5(*children: object, **attrs: Unpack[H5Attrs]) -> RenderFragment:
    return element("h5", children, attrs)


class H6Attrs(GlobalAttrs, total=False):
    pass


def H6(*children: object, **attrs: Unpack[H6Attrs]) -> RenderFragment:
    return element("h6", children, attrs)


class HeadAttrs(GlobalAttrs, total=False):
    pass


def Head(*children: object, **attrs: Unpack[HeadAttrs]) -> RenderFragment:
    return element("head", children, attrs)


class HeaderAttrs(GlobalAttrs, total=False):
    pass


def Header(*children: object, **attrs: Unpack[HeaderAttrs]) -> RenderFragment:
    return element("header", children, attrs)


class HrAttrs(GlobalAttrs, total=False):
    pass


def Hr(*children: object, **attrs: Unpack[HrAttrs]) -> RenderFragment:
    return element("hr", children, attrs)


class HtmlAttrs(GlobalAttrs, total=False):
    manifest: str | Signal[str] | None


def Html(*children: object, **attrs: Unpack[HtmlAttrs]) -> RenderFragment:
    return element("html", children, attrs)


class IAttrs(GlobalAttrs, total=False):
    pass


def I(*children: object, **attrs: Unpack[IAttrs]) -> RenderFragment:
    return element("i", children, attrs)


class IframeAttrs(GlobalAttrs, total=False):
    allow: str | Signal[str] | None
    allowfullscreen: bool | Signal[bool] | None
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    loading: str | Signal[str] | None
    name: str | Signal[str] | None
    referrerpolicy: str | Signal[str] | None
    sandbox: str | Signal[str] | None
    src: str | Signal[str] | None
    srcdoc: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Iframe(*children: object, **attrs: Unpack[IframeAttrs]) -> RenderFragment:
    return element("iframe", children, attrs)


class ImgAttrs(GlobalAttrs, total=False):
    alt: str | Signal[str] | None
    crossorigin: str | Signal[str] | None
    decoding: str | Signal[str] | None
    fetchpriority: str | Signal[str] | None
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    ismap: bool | Signal[bool] | None
    loading: str | Signal[str] | None
    referrerpolicy: str | Signal[str] | None
    sizes: str | Signal[str] | None
    src: str | Signal[str] | None
    srcset: str | Signal[str] | None
    usemap: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Img(*children: object, **attrs: Unpack[ImgAttrs]) -> RenderFragment:
    return element("img", children, attrs)


class InputAttrs(GlobalAttrs, total=False):
    accept: str | Signal[str] | None
    alt: str | Signal[str] | None
    autocomplete: str | Signal[str] | None
    capture: str | Signal[str] | None
    checked: bool | Signal[bool] | None
    dirname: str | Signal[str] | None
    disabled: bool | Signal[bool] | None
    form: str | Signal[str] | None
    formaction: str | Signal[str] | None
    formenctype: str | Signal[str] | None
    formmethod: str | Signal[str] | None
    formnovalidate: bool | Signal[bool] | None
    formtarget: str | Signal[str] | None
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    list: str | Signal[str] | None
    max: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    maxlength: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    min: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    minlength: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    multiple: bool | Signal[bool] | None
    name: str | Signal[str] | None
    pattern: str | Signal[str] | None
    placeholder: str | Signal[str] | None
    popovertarget: str | Signal[str] | None
    popovertargetaction: str | Signal[str] | None
    readonly: bool | Signal[bool] | None
    required: bool | Signal[bool] | None
    size: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    src: str | Signal[str] | None
    step: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    type: str | Signal[str] | None
    value: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    bind_value: Signal[str]
    bind_checked: Signal[bool]


def Input(*children: object, **attrs: Unpack[InputAttrs]) -> RenderFragment:
    return element("input", children, attrs)


class InsAttrs(GlobalAttrs, total=False):
    cite: str | Signal[str] | None
    datetime: str | Signal[str] | None


def Ins(*children: object, **attrs: Unpack[InsAttrs]) -> RenderFragment:
    return element("ins", children, attrs)


class KbdAttrs(GlobalAttrs, total=False):
    pass


def Kbd(*children: object, **attrs: Unpack[KbdAttrs]) -> RenderFragment:
    return element("kbd", children, attrs)


class LabelAttrs(GlobalAttrs, total=False):
    html_for: str | Signal[str] | None
    form: str | Signal[str] | None


def Label(*children: object, **attrs: Unpack[LabelAttrs]) -> RenderFragment:
    return element("label", children, attrs)


class LegendAttrs(GlobalAttrs, total=False):
    pass


def Legend(*children: object, **attrs: Unpack[LegendAttrs]) -> RenderFragment:
    return element("legend", children, attrs)


class LiAttrs(GlobalAttrs, total=False):
    value: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Li(*children: object, **attrs: Unpack[LiAttrs]) -> RenderFragment:
    return element("li", children, attrs)


class LinkAttrs(GlobalAttrs, total=False):
    as_: str | Signal[str] | None
    color: str | Signal[str] | None
    crossorigin: str | Signal[str] | None
    disabled: bool | Signal[bool] | None
    fetchpriority: str | Signal[str] | None
    href: str | Signal[str] | None
    hreflang: str | Signal[str] | None
    imagesizes: str | Signal[str] | None
    imagesrcset: str | Signal[str] | None
    integrity: str | Signal[str] | None
    media: str | Signal[str] | None
    referrerpolicy: str | Signal[str] | None
    rel: str | Signal[str] | None
    sizes: str | Signal[str] | None
    type: str | Signal[str] | None


def Link(*children: object, **attrs: Unpack[LinkAttrs]) -> RenderFragment:
    return element("link", children, attrs)


class MainAttrs(GlobalAttrs, total=False):
    pass


def Main(*children: object, **attrs: Unpack[MainAttrs]) -> RenderFragment:
    return element("main", children, attrs)


class MapAttrs(GlobalAttrs, total=False):
    name: str | Signal[str] | None


def Map(*children: object, **attrs: Unpack[MapAttrs]) -> RenderFragment:
    return element("map", children, attrs)


class MarkAttrs(GlobalAttrs, total=False):
    pass


def Mark(*children: object, **attrs: Unpack[MarkAttrs]) -> RenderFragment:
    return element("mark", children, attrs)


class MenuAttrs(GlobalAttrs, total=False):
    pass


def Menu(*children: object, **attrs: Unpack[MenuAttrs]) -> RenderFragment:
    return element("menu", children, attrs)


class MetaAttrs(GlobalAttrs, total=False):
    charset: str | Signal[str] | None
    content: str | Signal[str] | None
    http_equiv: str | Signal[str] | None
    media: str | Signal[str] | None
    name: str | Signal[str] | None


def Meta(*children: object, **attrs: Unpack[MetaAttrs]) -> RenderFragment:
    return element("meta", children, attrs)


class MeterAttrs(GlobalAttrs, total=False):
    form: str | Signal[str] | None
    high: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    low: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    max: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    min: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    optimum: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    value: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Meter(*children: object, **attrs: Unpack[MeterAttrs]) -> RenderFragment:
    return element("meter", children, attrs)


class NavAttrs(GlobalAttrs, total=False):
    pass


def Nav(*children: object, **attrs: Unpack[NavAttrs]) -> RenderFragment:
    return element("nav", children, attrs)


class NoscriptAttrs(GlobalAttrs, total=False):
    pass


def Noscript(*children: object, **attrs: Unpack[NoscriptAttrs]) -> RenderFragment:
    return element("noscript", children, attrs)


class ObjectAttrs(GlobalAttrs, total=False):
    data: str | Signal[str] | None
    form: str | Signal[str] | None
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    name: str | Signal[str] | None
    type: str | Signal[str] | None
    usemap: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Object(*children: object, **attrs: Unpack[ObjectAttrs]) -> RenderFragment:
    return element("object", children, attrs)


class OlAttrs(GlobalAttrs, total=False):
    reversed: bool | Signal[bool] | None
    start: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    type: str | Signal[str] | None


def Ol(*children: object, **attrs: Unpack[OlAttrs]) -> RenderFragment:
    return element("ol", children, attrs)


class OptgroupAttrs(GlobalAttrs, total=False):
    disabled: bool | Signal[bool] | None
    label: str | Signal[str] | None


def Optgroup(*children: object, **attrs: Unpack[OptgroupAttrs]) -> RenderFragment:
    return element("optgroup", children, attrs)


class OptionAttrs(GlobalAttrs, total=False):
    disabled: bool | Signal[bool] | None
    label: str | Signal[str] | None
    selected: bool | Signal[bool] | None
    value: str | Signal[str] | None


def Option(*children: object, **attrs: Unpack[OptionAttrs]) -> RenderFragment:
    return element("option", children, attrs)


class OutputAttrs(GlobalAttrs, total=False):
    html_for: str | Signal[str] | None
    form: str | Signal[str] | None
    name: str | Signal[str] | None


def Output(*children: object, **attrs: Unpack[OutputAttrs]) -> RenderFragment:
    return element("output", children, attrs)


class PAttrs(GlobalAttrs, total=False):
    pass


def P(*children: object, **attrs: Unpack[PAttrs]) -> RenderFragment:
    return element("p", children, attrs)


class ParamAttrs(GlobalAttrs, total=False):
    name: str | Signal[str] | None
    value: str | Signal[str] | None


def Param(*children: object, **attrs: Unpack[ParamAttrs]) -> RenderFragment:
    return element("param", children, attrs)


class PictureAttrs(GlobalAttrs, total=False):
    pass


def Picture(*children: object, **attrs: Unpack[PictureAttrs]) -> RenderFragment:
    return element("picture", children, attrs)


class PreAttrs(GlobalAttrs, total=False):
    pass


def Pre(*children: object, **attrs: Unpack[PreAttrs]) -> RenderFragment:
    return element("pre", children, attrs)


class ProgressAttrs(GlobalAttrs, total=False):
    max: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    value: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Progress(*children: object, **attrs: Unpack[ProgressAttrs]) -> RenderFragment:
    return element("progress", children, attrs)


class QAttrs(GlobalAttrs, total=False):
    cite: str | Signal[str] | None


def Q(*children: object, **attrs: Unpack[QAttrs]) -> RenderFragment:
    return element("q", children, attrs)


class RpAttrs(GlobalAttrs, total=False):
    pass


def Rp(*children: object, **attrs: Unpack[RpAttrs]) -> RenderFragment:
    return element("rp", children, attrs)


class RtAttrs(GlobalAttrs, total=False):
    pass


def Rt(*children: object, **attrs: Unpack[RtAttrs]) -> RenderFragment:
    return element("rt", children, attrs)


class RubyAttrs(GlobalAttrs, total=False):
    pass


def Ruby(*children: object, **attrs: Unpack[RubyAttrs]) -> RenderFragment:
    return element("ruby", children, attrs)


class SAttrs(GlobalAttrs, total=False):
    pass


def S(*children: object, **attrs: Unpack[SAttrs]) -> RenderFragment:
    return element("s", children, attrs)


class SampAttrs(GlobalAttrs, total=False):
    pass


def Samp(*children: object, **attrs: Unpack[SampAttrs]) -> RenderFragment:
    return element("samp", children, attrs)


class ScriptAttrs(GlobalAttrs, total=False):
    async_: bool | Signal[bool] | None
    crossorigin: str | Signal[str] | None
    defer: bool | Signal[bool] | None
    fetchpriority: str | Signal[str] | None
    integrity: str | Signal[str] | None
    nomodule: bool | Signal[bool] | None
    referrerpolicy: str | Signal[str] | None
    src: str | Signal[str] | None
    type: str | Signal[str] | None


def Script(*children: object, **attrs: Unpack[ScriptAttrs]) -> RenderFragment:
    return element("script", children, attrs)


class SectionAttrs(GlobalAttrs, total=False):
    pass


def Section(*children: object, **attrs: Unpack[SectionAttrs]) -> RenderFragment:
    return element("section", children, attrs)


class SelectAttrs(GlobalAttrs, total=False):
    autocomplete: str | Signal[str] | None
    disabled: bool | Signal[bool] | None
    form: str | Signal[str] | None
    multiple: bool | Signal[bool] | None
    name: str | Signal[str] | None
    required: bool | Signal[bool] | None
    size: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    bind_value: Signal[str]
    bind_selected: Signal[list[str]]


def Select(*children: object, **attrs: Unpack[SelectAttrs]) -> RenderFragment:
    return element("select", children, attrs)


class SlotAttrs(GlobalAttrs, total=False):
    name: str | Signal[str] | None


def Slot(*children: object, **attrs: Unpack[SlotAttrs]) -> RenderFragment:
    return element("slot", children, attrs)


class SmallAttrs(GlobalAttrs, total=False):
    pass


def Small(*children: object, **attrs: Unpack[SmallAttrs]) -> RenderFragment:
    return element("small", children, attrs)


class SourceAttrs(GlobalAttrs, total=False):
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    media: str | Signal[str] | None
    sizes: str | Signal[str] | None
    src: str | Signal[str] | None
    srcset: str | Signal[str] | None
    type: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Source(*children: object, **attrs: Unpack[SourceAttrs]) -> RenderFragment:
    return element("source", children, attrs)


class SpanAttrs(GlobalAttrs, total=False):
    pass


def Span(*children: object, **attrs: Unpack[SpanAttrs]) -> RenderFragment:
    return element("span", children, attrs)


class StrongAttrs(GlobalAttrs, total=False):
    pass


def Strong(*children: object, **attrs: Unpack[StrongAttrs]) -> RenderFragment:
    return element("strong", children, attrs)


class StyleAttrs(GlobalAttrs, total=False):
    media: str | Signal[str] | None


def Style(*children: object, **attrs: Unpack[StyleAttrs]) -> RenderFragment:
    return element("style", children, attrs)


class SubAttrs(GlobalAttrs, total=False):
    pass


def Sub(*children: object, **attrs: Unpack[SubAttrs]) -> RenderFragment:
    return element("sub", children, attrs)


class SummaryAttrs(GlobalAttrs, total=False):
    pass


def Summary(*children: object, **attrs: Unpack[SummaryAttrs]) -> RenderFragment:
    return element("summary", children, attrs)


class SupAttrs(GlobalAttrs, total=False):
    pass


def Sup(*children: object, **attrs: Unpack[SupAttrs]) -> RenderFragment:
    return element("sup", children, attrs)


class SvgAttrs(GlobalAttrs, total=False):
    pass


def Svg(*children: object, **attrs: Unpack[SvgAttrs]) -> RenderFragment:
    return element("svg", children, attrs)


class TableAttrs(GlobalAttrs, total=False):
    pass


def Table(*children: object, **attrs: Unpack[TableAttrs]) -> RenderFragment:
    return element("table", children, attrs)


class TbodyAttrs(GlobalAttrs, total=False):
    pass


def Tbody(*children: object, **attrs: Unpack[TbodyAttrs]) -> RenderFragment:
    return element("tbody", children, attrs)


class TdAttrs(GlobalAttrs, total=False):
    colspan: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    headers: str | Signal[str] | None
    rowspan: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Td(*children: object, **attrs: Unpack[TdAttrs]) -> RenderFragment:
    return element("td", children, attrs)


class TemplateAttrs(GlobalAttrs, total=False):
    pass


def Template(*children: object, **attrs: Unpack[TemplateAttrs]) -> RenderFragment:
    return element("template", children, attrs)


class TextareaAttrs(GlobalAttrs, total=False):
    autocomplete: str | Signal[str] | None
    cols: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    dirname: str | Signal[str] | None
    disabled: bool | Signal[bool] | None
    form: str | Signal[str] | None
    maxlength: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    minlength: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    name: str | Signal[str] | None
    placeholder: str | Signal[str] | None
    readonly: bool | Signal[bool] | None
    required: bool | Signal[bool] | None
    rows: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    wrap: str | Signal[str] | None
    bind_value: Signal[str]


def Textarea(*children: object, **attrs: Unpack[TextareaAttrs]) -> RenderFragment:
    return element("textarea", children, attrs)


class TfootAttrs(GlobalAttrs, total=False):
    pass


def Tfoot(*children: object, **attrs: Unpack[TfootAttrs]) -> RenderFragment:
    return element("tfoot", children, attrs)


class ThAttrs(GlobalAttrs, total=False):
    abbr: str | Signal[str] | None
    colspan: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    headers: str | Signal[str] | None
    rowspan: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    scope: str | Signal[str] | None


def Th(*children: object, **attrs: Unpack[ThAttrs]) -> RenderFragment:
    return element("th", children, attrs)


class TheadAttrs(GlobalAttrs, total=False):
    pass


def Thead(*children: object, **attrs: Unpack[TheadAttrs]) -> RenderFragment:
    return element("thead", children, attrs)


class TimeAttrs(GlobalAttrs, total=False):
    datetime: str | Signal[str] | None


def Time(*children: object, **attrs: Unpack[TimeAttrs]) -> RenderFragment:
    return element("time", children, attrs)


class TitleAttrs(GlobalAttrs, total=False):
    pass


def Title(*children: object, **attrs: Unpack[TitleAttrs]) -> RenderFragment:
    return element("title", children, attrs)


class TrAttrs(GlobalAttrs, total=False):
    pass


def Tr(*children: object, **attrs: Unpack[TrAttrs]) -> RenderFragment:
    return element("tr", children, attrs)


class TrackAttrs(GlobalAttrs, total=False):
    default_: bool | Signal[bool] | None
    kind: str | Signal[str] | None
    label: str | Signal[str] | None
    src: str | Signal[str] | None
    srclang: str | Signal[str] | None


def Track(*children: object, **attrs: Unpack[TrackAttrs]) -> RenderFragment:
    return element("track", children, attrs)


class UAttrs(GlobalAttrs, total=False):
    pass


def U(*children: object, **attrs: Unpack[UAttrs]) -> RenderFragment:
    return element("u", children, attrs)


class UlAttrs(GlobalAttrs, total=False):
    pass


def Ul(*children: object, **attrs: Unpack[UlAttrs]) -> RenderFragment:
    return element("ul", children, attrs)


class VarAttrs(GlobalAttrs, total=False):
    pass


def Var(*children: object, **attrs: Unpack[VarAttrs]) -> RenderFragment:
    return element("var", children, attrs)


class VideoAttrs(GlobalAttrs, total=False):
    autoplay: bool | Signal[bool] | None
    controls: bool | Signal[bool] | None
    crossorigin: str | Signal[str] | None
    height: int | float | str | Signal[int] | Signal[float] | Signal[str] | None
    loop: bool | Signal[bool] | None
    muted: bool | Signal[bool] | None
    playsinline: bool | Signal[bool] | None
    poster: str | Signal[str] | None
    preload: str | Signal[str] | None
    src: str | Signal[str] | None
    width: int | float | str | Signal[int] | Signal[float] | Signal[str] | None


def Video(*children: object, **attrs: Unpack[VideoAttrs]) -> RenderFragment:
    return element("video", children, attrs)


class WbrAttrs(GlobalAttrs, total=False):
    pass


def Wbr(*children: object, **attrs: Unpack[WbrAttrs]) -> RenderFragment:
    return element("wbr", children, attrs)


class MathAttrs(GlobalAttrs, total=False):
    pass


def Math(*children: object, **attrs: Unpack[MathAttrs]) -> RenderFragment:
    return element("math", children, attrs)
