"""Typed styled native factories. Generated by scripts/generate_native.py."""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from collections.abc import Mapping
    from string.templatelib import Template
    from typing import Protocol, Unpack

    from . import native
    from .reactive import Signal
    from .render import Fragment
    from .styled import Definition

    class AAttrs(native.AAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledA(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AAttrs]) -> Fragment: ...

    class AbbrAttrs(native.AbbrAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledAbbr(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AbbrAttrs]) -> Fragment: ...

    class AddressAttrs(native.AddressAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledAddress(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AddressAttrs]) -> Fragment: ...

    class AreaAttrs(native.AreaAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledArea(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AreaAttrs]) -> Fragment: ...

    class ArticleAttrs(native.ArticleAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledArticle(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ArticleAttrs]) -> Fragment: ...

    class AsideAttrs(native.AsideAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledAside(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AsideAttrs]) -> Fragment: ...

    class AudioAttrs(native.AudioAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledAudio(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[AudioAttrs]) -> Fragment: ...

    class BAttrs(native.BAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledB(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BAttrs]) -> Fragment: ...

    class BaseAttrs(native.BaseAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBase(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BaseAttrs]) -> Fragment: ...

    class BdiAttrs(native.BdiAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBdi(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BdiAttrs]) -> Fragment: ...

    class BdoAttrs(native.BdoAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBdo(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BdoAttrs]) -> Fragment: ...

    class BlockquoteAttrs(native.BlockquoteAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBlockquote(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BlockquoteAttrs]) -> Fragment: ...

    class BodyAttrs(native.BodyAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBody(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BodyAttrs]) -> Fragment: ...

    class BrAttrs(native.BrAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledBr(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[BrAttrs]) -> Fragment: ...

    class ButtonAttrs(native.ButtonAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledButton(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ButtonAttrs]) -> Fragment: ...

    class CanvasAttrs(native.CanvasAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledCanvas(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[CanvasAttrs]) -> Fragment: ...

    class CaptionAttrs(native.CaptionAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledCaption(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[CaptionAttrs]) -> Fragment: ...

    class CiteAttrs(native.CiteAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledCite(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[CiteAttrs]) -> Fragment: ...

    class CodeAttrs(native.CodeAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledCode(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[CodeAttrs]) -> Fragment: ...

    class ColAttrs(native.ColAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledCol(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ColAttrs]) -> Fragment: ...

    class ColgroupAttrs(native.ColgroupAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledColgroup(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ColgroupAttrs]) -> Fragment: ...

    class DataAttrs(native.DataAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledData(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DataAttrs]) -> Fragment: ...

    class DatalistAttrs(native.DatalistAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDatalist(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DatalistAttrs]) -> Fragment: ...

    class DdAttrs(native.DdAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDd(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DdAttrs]) -> Fragment: ...

    class DelAttrs(native.DelAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDel(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DelAttrs]) -> Fragment: ...

    class DetailsAttrs(native.DetailsAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDetails(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DetailsAttrs]) -> Fragment: ...

    class DfnAttrs(native.DfnAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDfn(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DfnAttrs]) -> Fragment: ...

    class DialogAttrs(native.DialogAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDialog(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DialogAttrs]) -> Fragment: ...

    class DivAttrs(native.DivAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDiv(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DivAttrs]) -> Fragment: ...

    class DlAttrs(native.DlAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDl(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DlAttrs]) -> Fragment: ...

    class DtAttrs(native.DtAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledDt(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[DtAttrs]) -> Fragment: ...

    class EmAttrs(native.EmAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledEm(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[EmAttrs]) -> Fragment: ...

    class EmbedAttrs(native.EmbedAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledEmbed(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[EmbedAttrs]) -> Fragment: ...

    class FieldsetAttrs(native.FieldsetAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledFieldset(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[FieldsetAttrs]) -> Fragment: ...

    class FigcaptionAttrs(native.FigcaptionAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledFigcaption(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[FigcaptionAttrs]) -> Fragment: ...

    class FigureAttrs(native.FigureAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledFigure(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[FigureAttrs]) -> Fragment: ...

    class FooterAttrs(native.FooterAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledFooter(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[FooterAttrs]) -> Fragment: ...

    class FormAttrs(native.FormAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledForm(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[FormAttrs]) -> Fragment: ...

    class H1Attrs(native.H1Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH1(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H1Attrs]) -> Fragment: ...

    class H2Attrs(native.H2Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH2(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H2Attrs]) -> Fragment: ...

    class H3Attrs(native.H3Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH3(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H3Attrs]) -> Fragment: ...

    class H4Attrs(native.H4Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH4(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H4Attrs]) -> Fragment: ...

    class H5Attrs(native.H5Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH5(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H5Attrs]) -> Fragment: ...

    class H6Attrs(native.H6Attrs, total=False):
        variant: str | Signal[str] | None

    class StyledH6(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[H6Attrs]) -> Fragment: ...

    class HeadAttrs(native.HeadAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledHead(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[HeadAttrs]) -> Fragment: ...

    class HeaderAttrs(native.HeaderAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledHeader(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[HeaderAttrs]) -> Fragment: ...

    class HrAttrs(native.HrAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledHr(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[HrAttrs]) -> Fragment: ...

    class HtmlAttrs(native.HtmlAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledHtml(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[HtmlAttrs]) -> Fragment: ...

    class IAttrs(native.IAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledI(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[IAttrs]) -> Fragment: ...

    class IframeAttrs(native.IframeAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledIframe(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[IframeAttrs]) -> Fragment: ...

    class ImgAttrs(native.ImgAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledImg(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ImgAttrs]) -> Fragment: ...

    class InputAttrs(native.InputAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledInput(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[InputAttrs]) -> Fragment: ...

    class InsAttrs(native.InsAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledIns(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[InsAttrs]) -> Fragment: ...

    class KbdAttrs(native.KbdAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledKbd(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[KbdAttrs]) -> Fragment: ...

    class LabelAttrs(native.LabelAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledLabel(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[LabelAttrs]) -> Fragment: ...

    class LegendAttrs(native.LegendAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledLegend(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[LegendAttrs]) -> Fragment: ...

    class LiAttrs(native.LiAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledLi(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[LiAttrs]) -> Fragment: ...

    class LinkAttrs(native.LinkAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledLink(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[LinkAttrs]) -> Fragment: ...

    class MainAttrs(native.MainAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMain(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MainAttrs]) -> Fragment: ...

    class MapAttrs(native.MapAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMap(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MapAttrs]) -> Fragment: ...

    class MarkAttrs(native.MarkAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMark(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MarkAttrs]) -> Fragment: ...

    class MenuAttrs(native.MenuAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMenu(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MenuAttrs]) -> Fragment: ...

    class MetaAttrs(native.MetaAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMeta(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MetaAttrs]) -> Fragment: ...

    class MeterAttrs(native.MeterAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMeter(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MeterAttrs]) -> Fragment: ...

    class NavAttrs(native.NavAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledNav(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[NavAttrs]) -> Fragment: ...

    class NoscriptAttrs(native.NoscriptAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledNoscript(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[NoscriptAttrs]) -> Fragment: ...

    class ObjectAttrs(native.ObjectAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledObject(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ObjectAttrs]) -> Fragment: ...

    class OlAttrs(native.OlAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledOl(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[OlAttrs]) -> Fragment: ...

    class OptgroupAttrs(native.OptgroupAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledOptgroup(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[OptgroupAttrs]) -> Fragment: ...

    class OptionAttrs(native.OptionAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledOption(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[OptionAttrs]) -> Fragment: ...

    class OutputAttrs(native.OutputAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledOutput(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[OutputAttrs]) -> Fragment: ...

    class PAttrs(native.PAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledP(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[PAttrs]) -> Fragment: ...

    class ParamAttrs(native.ParamAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledParam(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ParamAttrs]) -> Fragment: ...

    class PictureAttrs(native.PictureAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledPicture(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[PictureAttrs]) -> Fragment: ...

    class PreAttrs(native.PreAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledPre(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[PreAttrs]) -> Fragment: ...

    class ProgressAttrs(native.ProgressAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledProgress(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ProgressAttrs]) -> Fragment: ...

    class QAttrs(native.QAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledQ(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[QAttrs]) -> Fragment: ...

    class RpAttrs(native.RpAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledRp(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[RpAttrs]) -> Fragment: ...

    class RtAttrs(native.RtAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledRt(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[RtAttrs]) -> Fragment: ...

    class RubyAttrs(native.RubyAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledRuby(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[RubyAttrs]) -> Fragment: ...

    class SAttrs(native.SAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledS(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SAttrs]) -> Fragment: ...

    class SampAttrs(native.SampAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSamp(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SampAttrs]) -> Fragment: ...

    class ScriptAttrs(native.ScriptAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledScript(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ScriptAttrs]) -> Fragment: ...

    class SectionAttrs(native.SectionAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSection(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SectionAttrs]) -> Fragment: ...

    class SelectAttrs(native.SelectAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSelect(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SelectAttrs]) -> Fragment: ...

    class SlotAttrs(native.SlotAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSlot(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SlotAttrs]) -> Fragment: ...

    class SmallAttrs(native.SmallAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSmall(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SmallAttrs]) -> Fragment: ...

    class SourceAttrs(native.SourceAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSource(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SourceAttrs]) -> Fragment: ...

    class SpanAttrs(native.SpanAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSpan(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SpanAttrs]) -> Fragment: ...

    class StrongAttrs(native.StrongAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledStrong(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[StrongAttrs]) -> Fragment: ...

    class StyleAttrs(native.StyleAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledStyle(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[StyleAttrs]) -> Fragment: ...

    class SubAttrs(native.SubAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSub(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SubAttrs]) -> Fragment: ...

    class SummaryAttrs(native.SummaryAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSummary(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SummaryAttrs]) -> Fragment: ...

    class SupAttrs(native.SupAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSup(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SupAttrs]) -> Fragment: ...

    class SvgAttrs(native.SvgAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledSvg(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[SvgAttrs]) -> Fragment: ...

    class TableAttrs(native.TableAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTable(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TableAttrs]) -> Fragment: ...

    class TbodyAttrs(native.TbodyAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTbody(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TbodyAttrs]) -> Fragment: ...

    class TdAttrs(native.TdAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTd(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TdAttrs]) -> Fragment: ...

    class TemplateAttrs(native.TemplateAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTemplate(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TemplateAttrs]) -> Fragment: ...

    class TextareaAttrs(native.TextareaAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTextarea(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TextareaAttrs]) -> Fragment: ...

    class TfootAttrs(native.TfootAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTfoot(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TfootAttrs]) -> Fragment: ...

    class ThAttrs(native.ThAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTh(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[ThAttrs]) -> Fragment: ...

    class TheadAttrs(native.TheadAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledThead(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TheadAttrs]) -> Fragment: ...

    class TimeAttrs(native.TimeAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTime(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TimeAttrs]) -> Fragment: ...

    class TitleAttrs(native.TitleAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTitle(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TitleAttrs]) -> Fragment: ...

    class TrAttrs(native.TrAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTr(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TrAttrs]) -> Fragment: ...

    class TrackAttrs(native.TrackAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledTrack(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[TrackAttrs]) -> Fragment: ...

    class UAttrs(native.UAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledU(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[UAttrs]) -> Fragment: ...

    class UlAttrs(native.UlAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledUl(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[UlAttrs]) -> Fragment: ...

    class VarAttrs(native.VarAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledVar(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[VarAttrs]) -> Fragment: ...

    class VideoAttrs(native.VideoAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledVideo(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[VideoAttrs]) -> Fragment: ...

    class WbrAttrs(native.WbrAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledWbr(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[WbrAttrs]) -> Fragment: ...

    class MathAttrs(native.MathAttrs, total=False):
        variant: str | Signal[str] | None

    class StyledMath(Definition, Protocol):
        def __call__(self, *children: object, **attrs: Unpack[MathAttrs]) -> Fragment: ...


class NativeFactories:
    def a(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledA:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledA", build_styled(ElementTag("a"), css, variants))

    def abbr(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledAbbr:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledAbbr", build_styled(ElementTag("abbr"), css, variants))

    def address(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledAddress:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledAddress", build_styled(ElementTag("address"), css, variants))

    def area(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledArea:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledArea", build_styled(ElementTag("area"), css, variants))

    def article(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledArticle:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledArticle", build_styled(ElementTag("article"), css, variants))

    def aside(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledAside:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledAside", build_styled(ElementTag("aside"), css, variants))

    def audio(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledAudio:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledAudio", build_styled(ElementTag("audio"), css, variants))

    def b(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledB:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledB", build_styled(ElementTag("b"), css, variants))

    def base(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledBase:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBase", build_styled(ElementTag("base"), css, variants))

    def bdi(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledBdi:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBdi", build_styled(ElementTag("bdi"), css, variants))

    def bdo(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledBdo:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBdo", build_styled(ElementTag("bdo"), css, variants))

    def blockquote(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledBlockquote:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBlockquote", build_styled(ElementTag("blockquote"), css, variants))

    def body(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledBody:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBody", build_styled(ElementTag("body"), css, variants))

    def br(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledBr:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledBr", build_styled(ElementTag("br"), css, variants))

    def button(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledButton:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledButton", build_styled(ElementTag("button"), css, variants))

    def canvas(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledCanvas:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledCanvas", build_styled(ElementTag("canvas"), css, variants))

    def caption(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledCaption:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledCaption", build_styled(ElementTag("caption"), css, variants))

    def cite(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledCite:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledCite", build_styled(ElementTag("cite"), css, variants))

    def code(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledCode:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledCode", build_styled(ElementTag("code"), css, variants))

    def col(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledCol:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledCol", build_styled(ElementTag("col"), css, variants))

    def colgroup(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledColgroup:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledColgroup", build_styled(ElementTag("colgroup"), css, variants))

    def data(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledData:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledData", build_styled(ElementTag("data"), css, variants))

    def datalist(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledDatalist:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDatalist", build_styled(ElementTag("datalist"), css, variants))

    def dd(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDd:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDd", build_styled(ElementTag("dd"), css, variants))

    def del_(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDel:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDel", build_styled(ElementTag("del"), css, variants))

    def details(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledDetails:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDetails", build_styled(ElementTag("details"), css, variants))

    def dfn(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDfn:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDfn", build_styled(ElementTag("dfn"), css, variants))

    def dialog(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledDialog:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDialog", build_styled(ElementTag("dialog"), css, variants))

    def div(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDiv:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDiv", build_styled(ElementTag("div"), css, variants))

    def dl(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDl:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDl", build_styled(ElementTag("dl"), css, variants))

    def dt(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledDt:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledDt", build_styled(ElementTag("dt"), css, variants))

    def em(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledEm:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledEm", build_styled(ElementTag("em"), css, variants))

    def embed(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledEmbed:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledEmbed", build_styled(ElementTag("embed"), css, variants))

    def fieldset(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledFieldset:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledFieldset", build_styled(ElementTag("fieldset"), css, variants))

    def figcaption(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledFigcaption:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledFigcaption", build_styled(ElementTag("figcaption"), css, variants))

    def figure(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledFigure:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledFigure", build_styled(ElementTag("figure"), css, variants))

    def footer(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledFooter:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledFooter", build_styled(ElementTag("footer"), css, variants))

    def form(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledForm:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledForm", build_styled(ElementTag("form"), css, variants))

    def h1(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH1:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH1", build_styled(ElementTag("h1"), css, variants))

    def h2(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH2:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH2", build_styled(ElementTag("h2"), css, variants))

    def h3(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH3:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH3", build_styled(ElementTag("h3"), css, variants))

    def h4(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH4:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH4", build_styled(ElementTag("h4"), css, variants))

    def h5(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH5:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH5", build_styled(ElementTag("h5"), css, variants))

    def h6(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledH6:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledH6", build_styled(ElementTag("h6"), css, variants))

    def head(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledHead:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledHead", build_styled(ElementTag("head"), css, variants))

    def header(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledHeader:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledHeader", build_styled(ElementTag("header"), css, variants))

    def hr(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledHr:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledHr", build_styled(ElementTag("hr"), css, variants))

    def html(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledHtml:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledHtml", build_styled(ElementTag("html"), css, variants))

    def i(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledI:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledI", build_styled(ElementTag("i"), css, variants))

    def iframe(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledIframe:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledIframe", build_styled(ElementTag("iframe"), css, variants))

    def img(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledImg:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledImg", build_styled(ElementTag("img"), css, variants))

    def input(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledInput:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledInput", build_styled(ElementTag("input"), css, variants))

    def ins(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledIns:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledIns", build_styled(ElementTag("ins"), css, variants))

    def kbd(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledKbd:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledKbd", build_styled(ElementTag("kbd"), css, variants))

    def label(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledLabel:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledLabel", build_styled(ElementTag("label"), css, variants))

    def legend(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledLegend:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledLegend", build_styled(ElementTag("legend"), css, variants))

    def li(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledLi:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledLi", build_styled(ElementTag("li"), css, variants))

    def link(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledLink:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledLink", build_styled(ElementTag("link"), css, variants))

    def main(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMain:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMain", build_styled(ElementTag("main"), css, variants))

    def map(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMap:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMap", build_styled(ElementTag("map"), css, variants))

    def mark(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMark:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMark", build_styled(ElementTag("mark"), css, variants))

    def menu(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMenu:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMenu", build_styled(ElementTag("menu"), css, variants))

    def meta(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMeta:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMeta", build_styled(ElementTag("meta"), css, variants))

    def meter(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledMeter:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMeter", build_styled(ElementTag("meter"), css, variants))

    def nav(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledNav:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledNav", build_styled(ElementTag("nav"), css, variants))

    def noscript(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledNoscript:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledNoscript", build_styled(ElementTag("noscript"), css, variants))

    def object(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledObject:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledObject", build_styled(ElementTag("object"), css, variants))

    def ol(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledOl:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledOl", build_styled(ElementTag("ol"), css, variants))

    def optgroup(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledOptgroup:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledOptgroup", build_styled(ElementTag("optgroup"), css, variants))

    def option(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledOption:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledOption", build_styled(ElementTag("option"), css, variants))

    def output(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledOutput:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledOutput", build_styled(ElementTag("output"), css, variants))

    def p(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledP:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledP", build_styled(ElementTag("p"), css, variants))

    def param(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledParam:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledParam", build_styled(ElementTag("param"), css, variants))

    def picture(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledPicture:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledPicture", build_styled(ElementTag("picture"), css, variants))

    def pre(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledPre:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledPre", build_styled(ElementTag("pre"), css, variants))

    def progress(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledProgress:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledProgress", build_styled(ElementTag("progress"), css, variants))

    def q(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledQ:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledQ", build_styled(ElementTag("q"), css, variants))

    def rp(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledRp:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledRp", build_styled(ElementTag("rp"), css, variants))

    def rt(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledRt:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledRt", build_styled(ElementTag("rt"), css, variants))

    def ruby(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledRuby:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledRuby", build_styled(ElementTag("ruby"), css, variants))

    def s(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledS:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledS", build_styled(ElementTag("s"), css, variants))

    def samp(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSamp:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSamp", build_styled(ElementTag("samp"), css, variants))

    def script(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledScript:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledScript", build_styled(ElementTag("script"), css, variants))

    def section(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledSection:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSection", build_styled(ElementTag("section"), css, variants))

    def select(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledSelect:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSelect", build_styled(ElementTag("select"), css, variants))

    def slot(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSlot:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSlot", build_styled(ElementTag("slot"), css, variants))

    def small(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledSmall:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSmall", build_styled(ElementTag("small"), css, variants))

    def source(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledSource:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSource", build_styled(ElementTag("source"), css, variants))

    def span(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSpan:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSpan", build_styled(ElementTag("span"), css, variants))

    def strong(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledStrong:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledStrong", build_styled(ElementTag("strong"), css, variants))

    def style(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledStyle:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledStyle", build_styled(ElementTag("style"), css, variants))

    def sub(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSub:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSub", build_styled(ElementTag("sub"), css, variants))

    def summary(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledSummary:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSummary", build_styled(ElementTag("summary"), css, variants))

    def sup(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSup:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSup", build_styled(ElementTag("sup"), css, variants))

    def svg(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledSvg:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledSvg", build_styled(ElementTag("svg"), css, variants))

    def table(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTable:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTable", build_styled(ElementTag("table"), css, variants))

    def tbody(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTbody:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTbody", build_styled(ElementTag("tbody"), css, variants))

    def td(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledTd:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTd", build_styled(ElementTag("td"), css, variants))

    def template(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTemplate:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTemplate", build_styled(ElementTag("template"), css, variants))

    def textarea(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTextarea:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTextarea", build_styled(ElementTag("textarea"), css, variants))

    def tfoot(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTfoot:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTfoot", build_styled(ElementTag("tfoot"), css, variants))

    def th(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledTh:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTh", build_styled(ElementTag("th"), css, variants))

    def thead(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledThead:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledThead", build_styled(ElementTag("thead"), css, variants))

    def time(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledTime:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTime", build_styled(ElementTag("time"), css, variants))

    def title(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTitle:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTitle", build_styled(ElementTag("title"), css, variants))

    def tr(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledTr:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTr", build_styled(ElementTag("tr"), css, variants))

    def track(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledTrack:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledTrack", build_styled(ElementTag("track"), css, variants))

    def u(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledU:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledU", build_styled(ElementTag("u"), css, variants))

    def ul(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledUl:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledUl", build_styled(ElementTag("ul"), css, variants))

    def var(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledVar:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledVar", build_styled(ElementTag("var"), css, variants))

    def video(
        self, css: Template, *, variants: Mapping[str, Template] | None = None
    ) -> StyledVideo:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledVideo", build_styled(ElementTag("video"), css, variants))

    def wbr(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledWbr:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledWbr", build_styled(ElementTag("wbr"), css, variants))

    def math(self, css: Template, *, variants: Mapping[str, Template] | None = None) -> StyledMath:
        from .elements import ElementTag
        from .styled import build_styled

        return cast("StyledMath", build_styled(ElementTag("math"), css, variants))
