"""Generate native HTML signatures from the shared schema; --check detects drift."""

from __future__ import annotations

import argparse
import ast
import keyword
from pathlib import Path

from pysx.schema import (
    BASELINE_TAGS,
    BOOLEAN_ATTRS,
    EVENT_NAMES,
    GLOBAL_ATTRS,
    NUMBER_ATTRS,
    TAG_ATTRS,
    resolve_tag,
)

TARGET = Path(__file__).resolve().parents[1] / "pysx" / "native.py"
ALIASES = {"class": "class_name", "for": "html_for", "async": "async_", "default": "default_"}


def spelling(attr: str) -> str:
    name = ALIASES.get(attr, attr.replace("-", "_"))

    return name + "_" if keyword.iskeyword(name) else name


def annotation(attr: str, tag: str = "") -> str:
    if attr.startswith("on"):
        return "Callable[[object], object]"

    if attr in BOOLEAN_ATTRS:
        return "bool | Signal[bool] | None"

    if attr in NUMBER_ATTRS and not (
        attr == "value" and tag in {"input", "button", "option", "data", "param"}
    ):
        return "int | float | str | Signal[int] | Signal[float] | Signal[str] | None"

    return "str | Signal[str] | None"


def generate() -> str:
    lines = [
        '"""Typed native constructors. Generated by scripts/generate_native.py."""',
        "# ruff: noqa: N802, E743, TC001, TC003",
        "",
        "from collections.abc import Callable, Mapping",
        "from typing import TypedDict, Unpack",
        "",
        "from .native_support import custom_element as custom_element",
        "from .native_support import element",
        "from .reactive import Signal",
        "from .render import Fragment as RenderFragment",
        "",
        "",
        "class GlobalAttrs(TypedDict, total=False):",
    ]

    for attr in sorted(GLOBAL_ATTRS):
        lines.append(f"    {spelling(attr)}: {annotation(attr)}")

    for event in sorted(EVENT_NAMES):
        lines.append(f"    on_{event}: Callable[[object], object]")
    lines.append("    custom_attrs: Mapping[str, object]")
    tags = dict.fromkeys([resolve_tag(tag) for tag in BASELINE_TAGS] + ["math"])

    for tag in tags:
        title = tag.capitalize()
        parent = "TypedDict" if tag == "fragment" else "GlobalAttrs"
        lines += ["", "", f"class {title}Attrs({parent}, total=False):"]
        attrs = sorted(TAG_ATTRS.get(tag, frozenset()) - GLOBAL_ATTRS)
        lines += [f"    {spelling(attr)}: {annotation(attr, tag)}" for attr in attrs]

        if not attrs:
            lines.append("    pass")

        if tag in {"input", "textarea", "select"}:
            lines.append("    bind_value: Signal[str]")

        if tag == "input":
            lines.append("    bind_checked: Signal[bool]")

        if tag == "select":
            lines.append("    bind_selected: Signal[list[str]]")
        lines += [
            "",
            "",
            f"def {title}(*children: object, **attrs: Unpack[{title}Attrs]) -> RenderFragment:",
            f'    return element("{tag}", children, attrs)',
        ]

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generate()

    if args.check:
        if ast.dump(ast.parse(TARGET.read_text())) != ast.dump(ast.parse(source)):
            raise SystemExit("native signatures are stale; run the generator")
    else:
        TARGET.write_text(source)


if __name__ == "__main__":
    main()
