"""Generate native HTML signatures from the shared schema; --check detects drift."""

from __future__ import annotations

import argparse
import ast
import keyword
import re
import textwrap
from pathlib import Path

from pysx.schema import (
    BASELINE_TAGS,
    BOOLEAN_ATTRS,
    EVENT_NAMES,
    GLOBAL_ATTRS,
    NUMBER_ATTRS,
    TAG_ATTRS,
)

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "pysx" / "native.py"
CLIENT = ROOT / "pysx" / "static" / "client.js"
EVENTS_DECLARATION = re.compile(r"const EVENTS = \[[^\]]*\];")
ALIASES = {"class": "class_name", "for": "html_for", "async": "async_", "default": "default_"}


def spelling(attr: str) -> str:
    name = ALIASES.get(attr, attr.replace("-", "_"))

    return name + "_" if keyword.iskeyword(name) else name


def annotation(attr: str, tag: str = "") -> str:
    if attr.startswith("on"):
        return "Callable[[object], object] | EventHandler"

    if attr in BOOLEAN_ATTRS:
        return "bool | Signal[bool] | None"

    if attr in NUMBER_ATTRS and not (
        attr == "value" and tag in {"input", "button", "option", "data", "param"}
    ):
        return "int | float | str | Signal[int] | Signal[float] | Signal[str] | None"

    return "str | Signal[str] | None"


def generate() -> str:
    lines = [
        '"""Typed native constructors. Generated by scripts/generate_native.py."""',
        "# ruff: noqa: N802, E743, TC001, TC003",
        "",
        "from collections.abc import Callable, Mapping",
        "from string.templatelib import Template as StringTemplate",
        "from typing import TypedDict, Unpack",
        "",
        "from .dom import DomRef",
        "from .events import EventHandler",
        "from .native_support import custom_element as custom_element",
        "from .native_support import element",
        "from .reactive import Signal",
        "from .render import Fragment as RenderFragment",
        "",
        "",
        "class GlobalAttrs(TypedDict, total=False):",
    ]

    for attr in sorted(GLOBAL_ATTRS):
        lines.append(f"    {spelling(attr)}: {annotation(attr)}")

    for event in sorted(EVENT_NAMES):
        lines.append(f"    on_{event}: Callable[[object], object] | EventHandler")
    lines.append("    custom_attrs: Mapping[str, object]")
    lines.append("    ref: DomRef")
    lines.append("    css: str | StringTemplate | Signal[str]")
    lines.append("    style_vars: Mapping[str, str | Signal[str]] | Signal[dict[str, str]]")
    lines.append("    css_vars: Mapping[str, str | Signal[str]] | Signal[dict[str, str]]")
    tags = dict.fromkeys([*BASELINE_TAGS, "math"])

    for tag in tags:
        title = tag.capitalize()
        parent = "TypedDict" if tag == "fragment" else "GlobalAttrs"
        lines += ["", "", f"class {title}Attrs({parent}, total=False):"]
        attrs = sorted(TAG_ATTRS.get(tag, frozenset()) - GLOBAL_ATTRS)
        lines += [f"    {spelling(attr)}: {annotation(attr, tag)}" for attr in attrs]

        if not attrs:
            lines.append("    pass")

        if tag in {"input", "textarea", "select"}:
            lines.append("    bind_value: Signal[str]")

        if tag == "input":
            lines.append("    bind_checked: Signal[bool]")

        if tag == "select":
            lines.append("    bind_selected: Signal[list[str]]")
        lines += [
            "",
            "",
            f"def {title}(*children: object, **attrs: Unpack[{title}Attrs]) -> RenderFragment:",
            f'    return element("{tag}", children, attrs)',
        ]

    return "\n".join(lines) + "\n"


def delegated_events() -> list[str]:
    body = {attr[2:] for attr in TAG_ATTRS["body"] if attr.startswith("on")}

    return sorted(EVENT_NAMES | body)


def generate_client(current: str) -> str:
    joined = ", ".join(f'"{event}"' for event in delegated_events())
    body = textwrap.fill(joined, width=96, initial_indent="  ", subsequent_indent="  ")
    declaration = f"const EVENTS = [\n{body},\n];"

    if not EVENTS_DECLARATION.search(current):
        raise SystemExit("client.js has no EVENTS declaration to generate")

    return EVENTS_DECLARATION.sub(lambda _: declaration, current, count=1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generate()
    client = generate_client(CLIENT.read_text())

    if args.check:
        if ast.dump(ast.parse(TARGET.read_text())) != ast.dump(ast.parse(source)):
            raise SystemExit("native signatures are stale; run the generator")

        if CLIENT.read_text() != client:
            raise SystemExit("client event delegation is stale; run the generator")
    else:
        TARGET.write_text(source)
        CLIENT.write_text(client)


if __name__ == "__main__":
    main()
